version: '2.1'
services: 
    postgres:
        build: ./docker/postgres
        restart: always
        container_name: postgres
        ports:        
            - 32769:5432
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow_db
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "airflow_db", "-U", "airflow" ]
            timeout: 45s
            interval: 10s
            retries: 10

    airflow:
        build: ./docker/airflow
        restart: always
        container_name: airflow
        volumes:
            - ./airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./airflow/dags:/usr/local/airflow/dags
        ports:
            - 8080:8080
        healthcheck:
            test: [ "CMD", "nc", "-z", "airflow", "8080" ]
            timeout: 45s
            interval: 10s
            retries: 10

networks:
  default:
    name: airflow-network